name: OpenWrt Builder

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  REPO_BRANCH: v23.05.4
  WORKS_DIR: /workspace
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Init env
        run: |
          sudo apt-get -qq update
          # sudo apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p $WORKS_DIR
          sudo chown $USER:$GROUPS $WORKS_DIR
          echo 'Disk Information:'
          df -hT $WORKS_DIR
          echo 'Memory Information:'
          free
          
      - name: Clone source code
        working-directory: /workspace
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          ls -l $GITHUB_WORKSPACE

      - name: Update feeds
        run: pwd $GITHUB_WORKSPACE
       
          
          
          
    
           
